version: "3"
services:
  app1:
    image: manarelgamil/app1:latest
    container_name: app1
    ports:
      - '6000:6000'
    volumes:
      - .:/etc/data:ro

  app2:
    image: manarelgamil/app2:latest
    container_name: app2
    ports:
      - '5002:5002'
    volumes:
      - .:/etc/data:ro

